# Generated by Django 5.2 on 2025-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
