# Generated by Django 5.2 on 2025-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_forums_tg_username_news_tg_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forums',
            options={'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='forums',
            name='description',
            field=models.TextField(verbose_name="To'liq ma'zmunini kiriting"),
        ),
        migrations.AlterField(
            model_name='forums',
            name='image',
            field=models.ImageField(upload_to='main_images', verbose_name='Rasm tanlang'),
        ),
        migrations.AlterField(
            model_name='forums',
            name='min_desc',
            field=models.CharField(max_length=255, verbose_name="Qisqacha ma'zmuni"),
        ),
        migrations.AlterField(
            model_name='forums',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bog'lanish uchun telegram username"),
        ),
        migrations.AlterField(
            model_name='forums',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomini kiriting'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name="To'liq ma'zmunini kiriting"),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='main_images', verbose_name='Rasm tanlang'),
        ),
        migrations.AlterField(
            model_name='news',
            name='min_desc',
            field=models.CharField(max_length=255, verbose_name="Qisqacha ma'zmuni"),
        ),
        migrations.AlterField(
            model_name='news',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Bog'lanish uchun telegram username"),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomini kiriting'),
        ),
    ]
