# Generated by Django 5.2 on 2025-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_alter_forums_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Rasm tanlang')),
                ('title', models.CharField(max_length=255, verbose_name='Nomini kiriting')),
                ('annotatsiya', models.TextField(verbose_name='Annotatsiya')),
                ('keywords', models.TextField(verbose_name="Kalit so'zlar")),
                ('abstract', models.TextField(verbose_name='Abstarct')),
                ('keywords2', models.TextField(verbose_name='Keywords')),
                ('description', models.TextField(verbose_name="To'liq ma'zmunini kiriting")),
            ],
            options={
                'verbose_name': 'Nashriyot',
                'verbose_name_plural': 'Nashriyotlar',
            },
        ),
    ]
